Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import networkx as nx
import matplotlib.pyplot as plt

# Create a balanced tree
G = nx.balanced_tree(2, 3)

# Define a mapping from old labels to new labels
mapping = {0: r'$\emptyset$', 1: '0', 2: '1', 3: '00', 4: '01', 5: '10', 6: '11', 
           7: '000', 8: '001', 9: '010', 10: '011', 11: '100', 12: '101', 13: '110', 14: '111'}

# Apply the mapping to the graph
G = nx.relabel_nodes(G, mapping)

# Draw the graph
pos = nx.drawing.nx_agraph.graphviz_layout(G, prog='dot')

# Invert the y-coordinates to draw the graph upside down
pos = {node: (x, -y) for (node, (x, y)) in pos.items()}

# Draw the nodes with a larger size and a more transparent color
nx.draw(G, pos, with_labels=True, arrows=True, node_size=1000, node_color="blue", alpha=0.5)


# Show the plot
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/opt/anaconda3/lib/python3.11/site-packages/networkx/drawing/nx_agraph.py:295[0m, in [0;36mpygraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    294[0m [38;5;28;01mtry[39;00m:
[0;32m--> 295[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpygraphviz[39;00m
[1;32m    296[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m err:

[0;31mModuleNotFoundError[0m: No module named 'pygraphviz'

The above exception was the direct cause of the following exception:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 15[0m
[1;32m     12[0m G [38;5;241m=[39m nx[38;5;241m.[39mrelabel_nodes(G, mapping)
[1;32m     14[0m [38;5;66;03m# Draw the graph[39;00m
[0;32m---> 15[0m pos [38;5;241m=[39m nx[38;5;241m.[39mdrawing[38;5;241m.[39mnx_agraph[38;5;241m.[39mgraphviz_layout(G, prog[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdot[39m[38;5;124m'[39m)
[1;32m     17[0m [38;5;66;03m# Invert the y-coordinates to draw the graph upside down[39;00m
[1;32m     18[0m pos [38;5;241m=[39m {node: (x, [38;5;241m-[39my) [38;5;28;01mfor[39;00m (node, (x, y)) [38;5;129;01min[39;00m pos[38;5;241m.[39mitems()}

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/networkx/drawing/nx_agraph.py:251[0m, in [0;36mgraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    220[0m [38;5;28;01mdef[39;00m [38;5;21mgraphviz_layout[39m(G, prog[38;5;241m=[39m[38;5;124m"[39m[38;5;124mneato[39m[38;5;124m"[39m, root[38;5;241m=[39m[38;5;28;01mNone[39;00m, args[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m):
[1;32m    221[0m [38;5;250m    [39m[38;5;124;03m"""Create node positions for G using Graphviz.[39;00m
[1;32m    222[0m 
[1;32m    223[0m [38;5;124;03m    Parameters[39;00m
[0;32m   (...)[0m
[1;32m    249[0m [38;5;124;03m    see https://gitlab.com/graphviz/graphviz/-/issues/1767 for more info.[39;00m
[1;32m    250[0m [38;5;124;03m    """[39;00m
[0;32m--> 251[0m     [38;5;28;01mreturn[39;00m pygraphviz_layout(G, prog[38;5;241m=[39mprog, root[38;5;241m=[39mroot, args[38;5;241m=[39margs)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/networkx/drawing/nx_agraph.py:297[0m, in [0;36mpygraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    295[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpygraphviz[39;00m
[1;32m    296[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 297[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m    298[0m         [38;5;124m"[39m[38;5;124mrequires pygraphviz [39m[38;5;124m"[39m [38;5;124m"[39m[38;5;124mhttp://pygraphviz.github.io/[39m[38;5;124m"[39m
[1;32m    299[0m     ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    300[0m [38;5;28;01mif[39;00m root [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    301[0m     args [38;5;241m+[39m[38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124m-Groot=[39m[38;5;132;01m{[39;00mroot[38;5;132;01m}[39;00m[38;5;124m"[39m

[0;31mImportError[0m: requires pygraphviz http://pygraphviz.github.io/

